### ISSUE TITLE
More fractal

### ISSUE THREAD

**Issue by omriBernstein** [FullstackAcademy/fsg#15]

**Comment by ashryanbeats** [comment]
Omri, are you working on this?

**Comment by omriBernstein** [comment]
Well there's some discussion about whether we want this for fsg. But you should totally add your voice to that discussion if you wish.

And if we do decided to go down the fractal road, there's apparently a fair bit of documentation that we should also change.

Slack me or come find me tomorrow or the next day (etc) if you want to talk more about it.

**Comment by ashryanbeats** [comment]
Ok!

**Comment by joedotjs** [comment]
#16
