### ISSUE TITLE
angular-bootstrap

### ISSUE THREAD

**Issue by nickells** [FullstackAcademy/fsg#24]
My npm was having trouble installing angular-bootstrap, and it seems the [actual module is called "angular-bootstrap-npm"](https://www.npmjs.com/package/angular-bootstrap-npm). I changed my own package-json and it fixed the problem.

**Comment by joedotjs** [comment]
I haven't heard this issue before and `angular-bootstrap` is [an npm package](https://www.npmjs.com/package/angular-bootstrap). I would chalk this up to connectivity issues during `npm install` but I'll investigate.

Thanks, Nick!

**Comment by joedotjs** [comment]
Reference #25 

It seems `angular-bootstrap` changed its file structure out of the blue which broke how it was being linked in `server/app/views/index.html`. I'm merging @WesleyDRobinson 's for this.

Thanks again for the heads up!
