### ISSUE TITLE
Gulp-Sass breaks on Node 4.0.0

### ISSUE THREAD

**Issue by tashoecraft** [FullstackAcademy/fsg#26]
Had a problem where the version of Gulp/Node Sass is breaking when running Node 4.0.0. I deleted in package.son gulp-sass then ran npm install gulp-sass --save-dev and then reran nom install. I believe the version number needs to be adjusted to the latest release of gulp-sass. This also works on computers still running Node 0.14.

**Comment by joedotjs** [comment]
Thanks, @tashoecraft! As @seanjohnite referenced, e536951bffbd6f003f3b23ac24395324ba94f11d updated the version number. I also took the plunge that "required" >=4.0.0 in a92198d5038f851a9182a4a77c1bced102a8832c.
