### ISSUE TITLE
current angularbootstrap npm module outdated, change to angular-ui-boostrap

### ISSUE THREAD

**Issue by ariverox** [FullstackAcademy/fsg#29]
new version of ui bootstrap available in a different npm module. Supports popover templates and other features 
 angular-ui-bootstrap(https://www.npmjs.com/package/angular-ui-bootstrap)
 instead of the current angular-bootstrap (https://www.npmjs.com/package/angular-bootstrap).
 also requires ng- animate https://www.npmjs.com/package/angular-animate

**Comment by joedotjs** [comment]
Thanks, @ariverox! I implemented this in 63f8529b8e47f706c1ba8617c20df55fd9467179 and d6cbc8ec95a2ba00360bef6e2b00c115cd38c1f5.
