### ISSUE TITLE
Place files in a new folder

### ISSUE THREAD

**Issue by glebec** [FullstackAcademy/fsg#52]
I have on a couple of occasions typed `fsg` intending to `cd` into a folder *named* `fsg` (my shell doesn't require the `cd` command) but accidentally activated the `fsg` command instead. This is pretty annoying as it then places all the generated files into my current folder, requiring careful cleanup.

Admittedly this may be a minority case as probably >50% of people either must type `cd` or choose to type `cd`. However, even for that majority of people, they may expect `fsg` to create a folder and accidentally place app files in a parent folder instead.

I propose the following behavior:

* `fsg` — makes a new app in a new `fsg` folder by default.
* `fsg path/to/folder` — makes a new app in `path/to/folder` (recursively constructing the path if it doesn't already exist).

It wouldn't be a difficult addition; if you approve the idea I'd be happy to make the PR.

**Comment by joedotjs** [comment]
Yeah, this is fine. I can see this being a big pain. I've enhanced generation script to, if a process argument is given (like `fsg my-new-app`), a new directory with that name will be created and be the base directory of the fsg app. 594104b
